Improve default bash script boilerplate, and add a test file for pre-commit hook

diff --git a/misc/automate/git-hooks/post-checkout b/misc/automate/git-hooks/post-checkout
--- a/misc/automate/git-hooks/post-checkout
+++ b/misc/automate/git-hooks/post-checkout
@@ -1,7 +1,9 @@
 #!/bin/bash
-set -e
+set -e                    # Always die on error
+trap 'kill -HUP 0' SIGINT # Kill sub-processes when we're killed
+cd "$PROJECTNAME_ROOT"    # Start script in project root
 
 # This hook is called after `git checkout` (e.g `git checkout -b feature-branch` or `git checkout master`)
 
 echo "*** misc/automate/git-hooks/post-checkout: RUN setup-tools.sh"
-bash $PROJECTNAME_ROOT/misc/automate/setup-tools.sh
+./$PROJECTNAME_ROOT/misc/automate/setup-tools.sh
diff --git a/misc/automate/git-hooks/pre-commit b/misc/automate/git-hooks/pre-commit
--- a/misc/automate/git-hooks/pre-commit
+++ b/misc/automate/git-hooks/pre-commit
@@ -1,8 +1,9 @@
 #!/bin/bash
-set -e
+set -e                    # Always die on error
+trap 'kill -HUP 0' SIGINT # Kill sub-processes when we're killed
+cd "$PROJECTNAME_ROOT"    # Start script in project root
 
-# This hook is called on `git commit -m "commit msg"`, before the committed changes are actually applied.
-# If this hook exits with a non-0 code, the commit does not get applied.
+# This hook is called on `git commit -m "commit msg"`. If it exits with an error, the commit cancels.
 
 echo "*** misc/automate/git-hooks/pre-commit RUN TESTS"
-echo "TODO: bash scripts/tests/run-tests.sh"
+./scripts/test/pre-commit.sh
